--Average Daily Screen Time for Children
CREATE DATABASE ADST_DB;
USE ADST_DB;

CREATE TABLE ADST(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	AGE INT NOT NULL,
	GENDER VARCHAR(6) NOT NULL,
	SCREEN_TIME_TYPE VARCHAR(12) NOT NULL,
	DAY_TYPE CHAR(7) NOT NULL,
	AVERAGE_SCREEN_TIME NUMERIC(4,2) NOT NULL,
	SAMPLE_SIZE INT,
	CONSTRAINT GENDER_CHK CHECK (LOWER(GENDER) IN ('male', 'female', 'other')),
	CONSTRAINT SCREEN_TIME_TYPE_CHK CHECK (LOWER(SCREEN_TIME_TYPE) IN ('educational', 'recreational', 'total')),
	CONSTRAINT DAY_TYPE_CHK CHECK (LOWER(DAY_TYPE) IN ('weekend','weekday'))
);

INSERT INTO ADST 
SELECT AGE, 
CASE 
	WHEN GENDER = 'Other/Prefer not to say' THEN 'Other'
	ELSE GENDER
	END
, SCREEN_TIME_TYPE, DAY_TYPE, AVERAGE_SCREEN_TIME_HOURS, SAMPLE_SIZE FROM SCREEN_TIME;

SELECT * FROM ADST;

-- Retrieves all rows where the average screen time is greater than 2.0
SELECT * FROM ADST
WHERE AVERAGE_SCREEN_TIME > 2.0;

-- Retrieves all the unique screen time types from the table
SELECT DISTINCT SCREEN_TIME_TYPE FROM ADST;

-- Retrieves all rows where the screen time type is either Recreational or Educational and the day type is the Weekend, sorted by Gender, Age, then average screen time in descending order
SELECT * FROM ADST
WHERE SCREEN_TIME_TYPE IN ('Recreational', 'Educational')
AND DAY_TYPE = 'Weekend'
order by Gender, AGE, AVERAGE_SCREEN_TIME desc;

-- Retrieves a count of all rows in the table
SELECT COUNT(*) TOTAL_ROWS FROM ADST;

-- Retrieves a count of all genders in the table
SELECT GENDER, COUNT(*) TOTAL_PER_GENDER FROM ADST
GROUP BY GENDER;

--Retrieves the MIN, MAX, AVERAGE, and Standard deviation for the average screen time per gender
SELECT GENDER,
MIN(AVERAGE_SCREEN_TIME) MINIMUM_SCREEN_TIME_PER_GENDER,
MAX(AVERAGE_SCREEN_TIME) MAXIMUM_SCREEN_TIME_PER_GENDER,
AVG(AVERAGE_SCREEN_TIME) AVERAGE_SCREEN_TIME_PER_GENDER,
STDEV(AVERAGE_SCREEN_TIME) STANDARD_DEVIATION FROM ADST
GROUP BY GENDER;

SELECT GENDER,
MIN(AVERAGE_SCREEN_TIME) MINIMUM_SCREEN_TIME_PER_GENDER,
MAX(AVERAGE_SCREEN_TIME) MAXIMUM_SCREEN_TIME_PER_GENDER,
AVG(AVERAGE_SCREEN_TIME) AVERAGE_SCREEN_TIME_PER_GENDER,
STDEV(AVERAGE_SCREEN_TIME) STANDARD_DEVIATION FROM ADST
WHERE SCREEN_TIME_TYPE = 'Total' 
GROUP BY GENDER;

--Retrieves the MIN, MAX, AVERAGE, and Standard deviation for the average screen time per AGE
SELECT AGE,
MIN(AGE) MINIMUM_AGE_PER_AGE,
MAX(AGE) MAXIMUM_AGE_PER_AGE,
AVG(AGE) AVERAGE_AGE_PER_AGE,
STDEV(AGE) STANDARD_DEVIATION_AGE FROM ADST
GROUP BY AGE;

--Displays the running total of average screen time per gender
SELECT AGE,
GENDER,
SUM(AVERAGE_SCREEN_TIME) OVER (PARTITION BY GENDER ORDER BY ID) RUNNING_TOTAL_AVERAGE_SCREEN_TIME_PER_GENDER,
LEAD(AVERAGE_SCREEN_TIME) OVER (PARTITION BY GENDER ORDER BY ID) INCREASE 
FROM ADST;

--Displays the Average increase in screen time per gender
WITH AVG_GENDER_INC AS(
SELECT AGE,
GENDER,SUM(AVERAGE_SCREEN_TIME) OVER (PARTITION BY GENDER ORDER BY ID) RUNNING_TOTAL_AVERAGE_SCREEN_TIME_PER_GENDER,
LEAD(AVERAGE_SCREEN_TIME) OVER (PARTITION BY GENDER ORDER BY ID) INCREASE 
FROM ADST
)SELECT GENDER,ROUND(AVG(INCREASE),2) AVERAGE_INCREASE FROM AVG_GENDER_INC
GROUP BY GENDER;

--Displays the running total of average screen time per age group
SELECT AGE,
GENDER,
SUM(AVERAGE_SCREEN_TIME) OVER (PARTITION BY AGE ORDER BY ID) RUNNING_TOTAL_AVERAGE_SCREEN_TIME_PER_AGE,
LEAD(AVERAGE_SCREEN_TIME) OVER (PARTITION BY AGE ORDER BY ID) INCREASE 
FROM ADST
ORDER BY AGE;

--Displays the Average increase in screen time per age group
WITH AVG_AGE_INC AS(
SELECT AGE,
GENDER,
SUM(AVERAGE_SCREEN_TIME) OVER (PARTITION BY AGE ORDER BY ID) RUNNING_TOTAL_AVERAGE_SCREEN_TIME_PER_AGE,
LEAD(AVERAGE_SCREEN_TIME) OVER (PARTITION BY AGE ORDER BY ID) INCREASE 
FROM ADST
)SELECT AGE,ROUND(AVG(INCREASE),2) AVERAGE_INCREASE FROM AVG_AGE_INC
GROUP BY AGE;